### ISSUE TITLE
Problem during setup

### ISSUE THREAD

**Issue by Kwaice** [blakewedwards/l5r-lcg-octgn#11]
Not sure if this is on my end or not, but after starting a localhost game and both players loading decks, the setup seems to bug.

Player 1 uses setup, and his provinces appear to setup for Player 2 too, on P2's side, like a one-sided table.
Player 1 can't move his province either.
If Player 2 uses setup, his deck doesn't appear, and 2 first players token are on the table.

This happens using 2 octgn clients on the same computer. It didn't happen before.

**Comment by blakewedwards** [comment]
I reproduced this and I think it's because the game lobby is setting both players to side A. When both players have joined the lobby you should see an 'A' to the right of the 'Play' button in the row for their name. You can click this to toggle between 'A' and 'B'. As long as each player has a different value I think things are OK. Does this happen if you make a public lobby or just through direct connect? I can create an issue for the OCTGN client since it sounds like this is new.

**Comment by Kwaice** [comment]
Aaaah thank you ! Indeed that fixed it. 

I only tested it through direct connect.
